// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/ckhungaa/common/config"
	"github.com/ckhungaa/common/domain/repositories"
	"github.com/ckhungaa/contact/domain/repository"
	"github.com/ckhungaa/contact/domain/service"
	"github.com/ckhungaa/contact/server"
)

// Injectors from inject.go:

func injectSServer(ctx context.Context) (*server.ContactServer, error) {
	decoderConfigOption := config.ProvideDecodeOption(ctx)
	store := config.ProvideStore(ctx, decoderConfigOption)
	repositoriesConfig, err := repositories.ProvideConfig(ctx, store)
	if err != nil {
		return nil, err
	}
	baseRepository, err := repositories.ProvideBaseRepository(ctx, repositoriesConfig)
	if err != nil {
		return nil, err
	}
	repositoryRepository, err := repository.ProvideRepository(ctx, baseRepository)
	if err != nil {
		return nil, err
	}
	serviceService, err := service.ProvideService(ctx, repositoryRepository)
	if err != nil {
		return nil, err
	}
	contactServer, err := server.ProvideContact(ctx, serviceService)
	if err != nil {
		return nil, err
	}
	return contactServer, nil
}
