// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/ckhungaa/common/component/configs"
	"github.com/ckhungaa/common/component/repos"
	"github.com/ckhungaa/contact/domain/repository"
	"github.com/ckhungaa/contact/domain/service"
	"github.com/ckhungaa/contact/server"
)

// Injectors from inject.go:

func injectSServer(ctx context.Context) (*server.ContactServer, error) {
	decoderConfigOption := configs.ProvideDecodeOption(ctx)
	store := configs.ProvideStore(ctx, decoderConfigOption)
	config, err := repos.ProvideConfig(ctx, store)
	if err != nil {
		return nil, err
	}
	baseRepository, err := repos.ProvideBaseRepository(ctx, config)
	if err != nil {
		return nil, err
	}
	repositoryRepository, err := repository.ProvideRepository(ctx, baseRepository)
	if err != nil {
		return nil, err
	}
	serviceService, err := service.ProvideService(ctx, repositoryRepository)
	if err != nil {
		return nil, err
	}
	contactServer, err := server.ProvideContact(ctx, serviceService)
	if err != nil {
		return nil, err
	}
	return contactServer, nil
}
